### ISSUE TITLE
Unable to copy logs from tab

### ISSUE THREAD

**Issue by mezbahalam** [y-takey/rails-dashboard#2]
Hi @y-takey ,

This app is great !! There is no doubt here. 
But i'm unable to  **copy logs**  from tab. 
Am i missing something ? Or this app need to add that feature.

Thanks,
Mezbah

**Comment by y-takey** [comment]
Hi @mezbahalam ,

Thanks for the report. :) I guess it's a bug, so I'll fix this issue!

Regards,

**Comment by y-takey** [comment]
Hi @mezbahalam ,

I've fixed this issue, and published a newer package :) 
Please check it when you have time if you'd like. (after run `npm update -g rails-dashboard` or `yarn global upgrade rails-dashboard`)

Thanks,
y-takey

**Comment by mezbahalam** [comment]
@y-takey , its working great .
Thank you.
