### ISSUE TITLE
Not work with Rails4.2.9

### ISSUE THREAD

**Issue by raykin** [y-takey/rails-dashboard#4]
I've tried using it on my iTerm2, but not work. It first show Booting... in the center screen then nothing happened. There are no rails and ruby process too.
I use 
```
npx rails-dashboard rails s
```
to start.
Here is a few env.
```
~/studio/captivereach (self-learn ✘)✹ ᐅ node --version
v8.4.0
~/studio/captivereach (self-learn ✘)✹ ᐅ npm --version
5.4.2
~/studio/captivereach (self-learn ✘)✹ ᐅ bundle list rails
b/Users/raykin/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/rails-4.2.9
~/studio/captivereach (self-learn ✘)✹ ᐅ bundle list puma
/Users/raykin/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/puma-3.10.0
```
There are no log in development.log
So where can I get more debug informations?

**Comment by y-takey** [comment]
Hi @raykin ,

Thanks for the report :) 
Unfortunately, currently supported rails is 5.1 or higher. but if you need to support rails 4.2, I will support one. It may also take while.

**Comment by raykin** [comment]
@y-takey thanks for your response. Actually I can help the process too if you can give me advice on how it work or where I can find the logs. I guess somewhere should happen crash.

**Comment by y-takey** [comment]
Awesome! 
This tool don't output logs, so you should debug to find the problem. see [README](https://github.com/y-takey/rails-dashboard#development) about how to develop.

1. [here](https://github.com/y-takey/rails-dashboard/blob/master/bin/rails-dashboard.js#L22) is point that execute the rails process actually. Please try to output the log. e.g.
```js
console.log("parameter:", command, args);  // ADD thils line
const child = spawn(command, args, {
  stdio: [null, null, null, null],
  detached: true
});
```
2. [here](https://github.com/y-takey/rails-dashboard/blob/master/src/parser.js#L184) is follows all rails logs. add console.log to see the logs. Then try to check the log format and expected format in `parser.js` .
```js
const ret = lines.map(line => {
  console.log(line); // ADD this line
  const l = removeANSIstyles(line).trim();

```
