### ISSUE TITLE
scrolling in log view 

### ISSUE THREAD

**Issue by Liooo** [y-takey/rails-dashboard#5]
Is it possible to scroll down in the log view?
Currently if the raw log is long, I can't see the end of it. (necessary when checking internal server errors detail etc)

**Comment by y-takey** [comment]
Hi @Liooo ,

Yes, it is possible to scroll down. However it needs a setting probably.
For example in Terminal.app, you should allow mouse reporting. on menu [View] → [Allow Mouse Reporting](in japanese, [表示] → [マウスレポーティングを許可])

I hope it will help you.

**Comment by Liooo** [comment]
Thanks for the response. (日本語での表記もご丁寧に追加して頂きありがとうございましたm(_ _)m)

I'm using iTerm2/OSX, and this is the equivalent in iTerm2, right?

<img width="707" alt="screen shot 2017-11-08 at 6 42 12 pm" src="https://user-images.githubusercontent.com/1630378/32542043-c7fa6fd4-c4b4-11e7-94cf-873d52d1505a.png">

I turned them on and scrolled with trackpad but it's not scrolling.. (created a new rails 5.1 app, added a long line debug print and ran `rails-dashboard ./bin/rails s`)
Am I missing something?

```
⇒  rails-dashboard --version
0.1.6

⇒  node --version
v6.11.4
```

**Comment by Liooo** [comment]
Also, I thought it'd be really awesome for keyboard people to be able to scroll inside subview without using mouse. Maybe `Shift + j` and `Shift+k` (like tig's default setting for scrolling the non-focused ish view) or something?

Anyway, thanks for the great tool I love it.

**Comment by y-takey** [comment]
Thanks for the reply :)

I could reproduce the issue on iTerm2. By the way,

> Maybe Shift + j and Shift+k (like tig's default setting for scrolling the non-focused ish view) or something?

Looks good to me! I agree completely your idea. I will improve to scroll inside subview using keyboard only.
In fact, i didn't know that tig able to scroll the non-focused view using `Shift + key` :(

**Comment by Liooo** [comment]
> I could reproduce the issue on iTerm2. 

Could I ask you to fix that for me? 👴 

> I will improve to scroll inside subview using keyboard only.

Thank you! I'll be looking forward to that.

> In fact, i didn't know that tig able to scroll the non-focused view using Shift + key :(

Yea It's really convenient :)

**Comment by y-takey** [comment]
> Could I ask you to fix that for me?

すみません、解釈を間違ってるといけないので日本語で失礼します m(_ _)m
こちらは@Liooo さんに修正していただける、という解釈であっていますか？
もしそうでしたら、もちろん大歓迎です。違う場合でも、私の方で色々調査してみますが、知識不足もあり確実に修正できるとは言えない状況です。
そういう事情もあり、キーボードで代替できるように考えています。（こちらはほぼ確実です）

日本語で甘えさせてもらい失礼しました・・

**Comment by Liooo** [comment]
@y-takey さんに修正していただくことはできますでしょうか？ の丁寧バージョンです。笑

> もしそうでしたら、もちろん大歓迎です。違う場合でも、私の方で色々調査してみますが、知識不足もあり確実に修正できるとは言えない状況です。

了解です。自分の方でも何かできるか見てみますね。

> 日本語で甘えさせてもらい失礼しました
いえいえ、上記やりとりで十分にissueの概要は列挙できてると思うので m(_ _)m

**Comment by y-takey** [comment]
Thank you for your kind words :) I'll try to fix this issue.

**Comment by y-takey** [comment]
I've improved scrolling and publish the newer version. Could you try after run following command and update your package?

To be enable scroll on iTerm2,
```
$ defaults write com.googlecode.iterm2 AlternateMouseScroll -bool true
```
about the detail, see [README](https://github.com/y-takey/rails-dashboard#iterm2app)

**Comment by Liooo** [comment]
Everything is working great, thanks @y-takey!
Will start using this plugin for my rails dev :)
